#!/usr/bin/env python3
"""
RDP Disconnect Testing Framework - Command Line Interface

Surgical, protocol-aware RDP disconnect testing tool built on Aardwolf.
"""

import sys
from aardwolf.testing.cli import main

if __name__ == '__main__':
	sys.exit(main())
